### ISSUE TITLE
Force field API for the Isotherm workchain.

### ISSUE THREAD

**Issue by yakutovicha** [lsmo-epfl/aiida-lsmo#41]
Currently, to create a new molecule one needs to specify its parameters in two different places:

- [isotherm_molecules](https://github.com/lsmo-epfl/aiida-lsmo/blob/develop/aiida_lsmo/workchains/isotherm_data/isotherm_molecules.yaml)
- [ff_data.yaml](https://github.com/lsmo-epfl/aiida-lsmo/blob/develop/aiida_lsmo/calcfunctions/ff_data.yaml)

I believe this separation is not necessary, since: 

1.  The parameters, provided in the `isotherm_data` are forcefield dependent.
2. The separation makes adding a new molecule quite confusing.
3. The implementation becomes quite complex.
4. The current implementation does not allow to provide a new molecule force field dictionary as the isotherm input.

<h2> My proposition</h2>

I would propose to make `ff_data.yaml` to be the single source of truth. So the definition of hydrogen would look as follows:
```yaml
H2:
  critical_constants:
    tc: 33.18
    pc: 1313000
    af: 0.0
    defaultff: MDT+DL  # NEW
  MDT+DL:
    description: >-
      Some description
    molsatdens: 35.4  # NEW
    proberad: 1.48  # NEW
    singlebead: False  # NEW
    charged: True # NEW
    atom_types:
      H_h2:
        force_field: [zero-potential]
        pseudo_atom: [yes, H, H, 0, 1.0, +0.468, 0.0, 1.0, 1.00, 0, 0, relative, 0]
      M_h2:
        force_field: [feynman-hibbs-lennard-jones, 36.7, 2.958, 1.0] # epsilon, sigma, reduced mass H2-H2 (amu
        force_field_mix: [lennard-jones, 36.7, 2.958]
        pseudo_atom: [no, M, M, 0, 0.0, -0.936, 0.0, 1.0, 1.00, 0, 0, relative, 0]
    atomic_positions:
      - [H_h2, 0, 0, -0.3705]
      - [M_h2, 0, 0, 0]
      - [H_h2, 0, 0, +0.3705]
```

The molecule input would look something like:
```python
builder.molecule = "H2[MDT+DL]" # [MDT+DL] is optional
```
`[MDT+DL]` is optional and, in case not provided, will be set to the value of `defaultff` from the YAML file. I would also allow resetting the FF as follows:
```python
builder.molecule_ff = {
    "_": "merge",  # can be "merge" to merge to the existing ff or "replace" to replace the FF entirely.
    "molsatdens": 36.00,
    "atom_types": {
        "H_h2": {
             "force_field": ["zero-potential"]
        }
    }
}
```

This `builder.molecule_ff` will append the new data to the selected forcefield.
